-- 0009_normalize_countries.sql
-- Normalizes user & asset country values to canonical Spanish names.
-- Safe to run multiple times. Case-sensitive matches on known variants.

UPDATE users SET country='Afganistán' WHERE country='Afghanistan';
UPDATE users SET country='Argelia' WHERE country='Algeria';
UPDATE users SET country='Antigua y Barbuda' WHERE country='Antigua and Barbuda';
UPDATE users SET country='Azerbaiyán' WHERE country='Azerbaijan';
UPDATE users SET country='Baréin' WHERE country='Bahrain';
UPDATE users SET country='Bangladés' WHERE country='Bangladesh';
UPDATE users SET country='Bielorrusia' WHERE country='Belarus';
UPDATE users SET country='Bélgica' WHERE country='Belgium';
UPDATE users SET country='Belice' WHERE country='Belize';
UPDATE users SET country='Benín' WHERE country='Benin';
UPDATE users SET country='Bután' WHERE country='Bhutan';
UPDATE users SET country='Bosnia y Herzegovina' WHERE country='Bosnia and Herzegovina';
UPDATE users SET country='Botsuana' WHERE country='Botswana';
UPDATE users SET country='Brasil' WHERE country='Brazil';
UPDATE users SET country='Brunéi' WHERE country='Brunei';
UPDATE users SET country='Camboya' WHERE country='Cambodia';
UPDATE users SET country='Camerún' WHERE country='Cameroon';
UPDATE users SET country='Canadá' WHERE country='Canada';
UPDATE users SET country='Cabo Verde' WHERE country='Cape Verde';
UPDATE users SET country='República Centroafricana' WHERE country='Central African Republic';
UPDATE users SET country='Comoras' WHERE country='Comoros';
UPDATE users SET country='Croacia' WHERE country='Croatia';
UPDATE users SET country='Chipre' WHERE country='Cyprus';
UPDATE users SET country='República Checa' WHERE country='Czech Republic';
UPDATE users SET country='Dinamarca' WHERE country='Denmark';
UPDATE users SET country='Yibuti' WHERE country='Djibouti';
UPDATE users SET country='República Dominicana' WHERE country='Dominican Republic';
UPDATE users SET country='Egipto' WHERE country='Egypt';
UPDATE users SET country='Guinea Ecuatorial' WHERE country='Equatorial Guinea';
UPDATE users SET country='Esuatini' WHERE country='Eswatini';
UPDATE users SET country='Etiopía' WHERE country='Ethiopia';
UPDATE users SET country='Fiyi' WHERE country='Fiji';
UPDATE users SET country='Finlandia' WHERE country='Finland';
UPDATE users SET country='Francia' WHERE country='France';
UPDATE users SET country='Gabón' WHERE country='Gabon';
UPDATE users SET country='Alemania' WHERE country='Germany';
UPDATE users SET country='Grecia' WHERE country='Greece';
UPDATE users SET country='Granada' WHERE country='Grenada';
UPDATE users SET country='Guinea-Bisáu' WHERE country='Guinea-Bissau';
UPDATE users SET country='Haití' WHERE country='Haiti';
UPDATE users SET country='Hungría' WHERE country='Hungary';
UPDATE users SET country='Islandia' WHERE country='Iceland';
UPDATE users SET country='Irán' WHERE country='Iran';
UPDATE users SET country='Irak' WHERE country='Iraq';
UPDATE users SET country='Irlanda' WHERE country='Ireland';
UPDATE users SET country='Italia' WHERE country='Italy';
UPDATE users SET country='Costa de Marfil' WHERE country='Ivory Coast';
UPDATE users SET country='Japón' WHERE country='Japan';
UPDATE users SET country='Jordania' WHERE country='Jordan';
UPDATE users SET country='Kazajistán' WHERE country='Kazakhstan';
UPDATE users SET country='Kenia' WHERE country='Kenya';
UPDATE users SET country='Kirguistán' WHERE country='Kyrgyzstan';
UPDATE users SET country='Letonia' WHERE country='Latvia';
UPDATE users SET country='Líbano' WHERE country='Lebanon';
UPDATE users SET country='Lesoto' WHERE country='Lesotho';
UPDATE users SET country='Libia' WHERE country='Libya';
UPDATE users SET country='Lituania' WHERE country='Lithuania';
UPDATE users SET country='Luxemburgo' WHERE country='Luxembourg';
UPDATE users SET country='Malaui' WHERE country='Malawi';
UPDATE users SET country='Malasia' WHERE country='Malaysia';
UPDATE users SET country='Maldivas' WHERE country='Maldives';
UPDATE users SET country='Malí' WHERE country='Mali';
UPDATE users SET country='Islas Marshall' WHERE country='Marshall Islands';
UPDATE users SET country='Mauricio' WHERE country='Mauritius';
UPDATE users SET country='México' WHERE country='Mexico';
UPDATE users SET country='Moldavia' WHERE country='Moldova';
UPDATE users SET country='Mónaco' WHERE country='Monaco';
UPDATE users SET country='Marruecos' WHERE country='Morocco';
UPDATE users SET country='Birmania' WHERE country='Myanmar';
UPDATE users SET country='Países Bajos' WHERE country='Netherlands';
UPDATE users SET country='Nueva Zelanda' WHERE country='New Zealand';
UPDATE users SET country='Níger' WHERE country='Niger';
UPDATE users SET country='Corea del Norte' WHERE country='North Korea';
UPDATE users SET country='Macedonia del Norte' WHERE country='North Macedonia';
UPDATE users SET country='Noruega' WHERE country='Norway';
UPDATE users SET country='Omán' WHERE country='Oman';
UPDATE users SET country='Pakistán' WHERE country='Pakistan';
UPDATE users SET country='Palaos' WHERE country='Palau';
UPDATE users SET country='Palestina' WHERE country='Palestine';
UPDATE users SET country='Panamá' WHERE country='Panama';
UPDATE users SET country='Papúa Nueva Guinea' WHERE country='Papua New Guinea';
UPDATE users SET country='Perú' WHERE country='Peru';
UPDATE users SET country='Filipinas' WHERE country='Philippines';
UPDATE users SET country='Polonia' WHERE country='Poland';
UPDATE users SET country='Catar' WHERE country='Qatar';
UPDATE users SET country='Rumanía' WHERE country='Romania';
UPDATE users SET country='Rusia' WHERE country='Russia';
UPDATE users SET country='Ruanda' WHERE country='Rwanda';
UPDATE users SET country='San Cristóbal y Nieves' WHERE country='Saint Kitts and Nevis';
UPDATE users SET country='Santa Lucía' WHERE country='Saint Lucia';
UPDATE users SET country='San Vicente y las Granadinas' WHERE country='Saint Vincent and the Grenadines';
UPDATE users SET country='Santo Tomé y Príncipe' WHERE country='Sao Tome and Principe';
UPDATE users SET country='Arabia Saudita' WHERE country='Saudi Arabia';
UPDATE users SET country='Sierra Leona' WHERE country='Sierra Leone';
UPDATE users SET country='Singapur' WHERE country='Singapore';
UPDATE users SET country='Eslovaquia' WHERE country='Slovakia';
UPDATE users SET country='Eslovenia' WHERE country='Slovenia';
UPDATE users SET country='Islas Salomón' WHERE country='Solomon Islands';
UPDATE users SET country='Sudáfrica' WHERE country='South Africa';
UPDATE users SET country='Corea del Sur' WHERE country='South Korea';
UPDATE users SET country='Sudán del Sur' WHERE country='South Sudan';
UPDATE users SET country='España' WHERE country='Spain';
UPDATE users SET country='Sudán' WHERE country='Sudan';
UPDATE users SET country='Surinam' WHERE country='Suriname';
UPDATE users SET country='Suecia' WHERE country='Sweden';
UPDATE users SET country='Suiza' WHERE country='Switzerland';
UPDATE users SET country='Siria' WHERE country='Syria';
UPDATE users SET country='Taiwán' WHERE country='Taiwan';
UPDATE users SET country='Tayikistán' WHERE country='Tajikistan';
UPDATE users SET country='Tailandia' WHERE country='Thailand';
UPDATE users SET country='Timor Oriental' WHERE country='Timor-Leste';
UPDATE users SET country='Trinidad y Tobago' WHERE country='Trinidad and Tobago';
UPDATE users SET country='Túnez' WHERE country='Tunisia';
UPDATE users SET country='Turquía' WHERE country='Turkey';
UPDATE users SET country='Turkmenistán' WHERE country='Turkmenistan';
UPDATE users SET country='Ucrania' WHERE country='Ukraine';
UPDATE users SET country='Emiratos Árabes Unidos' WHERE country='United Arab Emirates';
UPDATE users SET country='Reino Unido' WHERE country='United Kingdom';
UPDATE users SET country='Estados Unidos' WHERE country='United States';
UPDATE users SET country='Uzbekistán' WHERE country='Uzbekistan';
UPDATE users SET country='Ciudad del Vaticano' WHERE country='Vatican City';
UPDATE users SET country='Zimbabue' WHERE country='Zimbabwe';
UPDATE users SET country='México' WHERE country='Mexico';
UPDATE users SET country='México' WHERE country='Méjico';
UPDATE users SET country='Perú' WHERE country='Peru';
UPDATE users SET country='Panamá' WHERE country='Panama';
UPDATE users SET country='España' WHERE country='Espana';
UPDATE users SET country='Estados Unidos' WHERE country='USA';
UPDATE users SET country='Estados Unidos' WHERE country='U.S.A.';
UPDATE users SET country='Estados Unidos' WHERE country='US';
UPDATE users SET country='Estados Unidos' WHERE country='U.S.';
UPDATE users SET country='Estados Unidos' WHERE country='EEUU';
UPDATE users SET country='Estados Unidos' WHERE country='EE.UU.';
UPDATE users SET country='Estados Unidos' WHERE country='EE UU';
UPDATE users SET country='Reino Unido' WHERE country='UK';
UPDATE users SET country='Reino Unido' WHERE country='U.K.';
UPDATE users SET country='Brasil' WHERE country='Brasil ';
UPDATE users SET country='Ucrania' WHERE country='Ucrania ';
UPDATE users SET country='Panamá' WHERE country='Panamá ';
UPDATE users SET country='República Dominicana' WHERE country='Republica Dominicana';
UPDATE users SET country='Perú' WHERE country='Peru ';
UPDATE users SET country='Emiratos Árabes Unidos' WHERE country='Emiratos Arabes Unidos';
UPDATE users SET country='Bélgica' WHERE country='Belgica';
UPDATE users SET country='Japón' WHERE country='Japon';
UPDATE users SET country='Líbano' WHERE country='Libano';
UPDATE users SET country='Turquía' WHERE country='Turquia';
UPDATE users SET country='Rumanía' WHERE country='Rumania';
UPDATE users SET country='Etiopía' WHERE country='Etiopia';
UPDATE users SET country='Haití' WHERE country='Haiti';
UPDATE users SET country='Irán' WHERE country='Iran';
UPDATE users SET country='Nigeria' WHERE country='Nigeria ';

-- Assets table (some assets also carry a country tag)
UPDATE assets SET country='Afganistán' WHERE country='Afghanistan';
UPDATE assets SET country='Argelia' WHERE country='Algeria';
UPDATE assets SET country='Antigua y Barbuda' WHERE country='Antigua and Barbuda';
UPDATE assets SET country='Azerbaiyán' WHERE country='Azerbaijan';
UPDATE assets SET country='Baréin' WHERE country='Bahrain';
UPDATE assets SET country='Bangladés' WHERE country='Bangladesh';
UPDATE assets SET country='Bielorrusia' WHERE country='Belarus';
UPDATE assets SET country='Bélgica' WHERE country='Belgium';
UPDATE assets SET country='Belice' WHERE country='Belize';
UPDATE assets SET country='Benín' WHERE country='Benin';
UPDATE assets SET country='Bután' WHERE country='Bhutan';
UPDATE assets SET country='Bosnia y Herzegovina' WHERE country='Bosnia and Herzegovina';
UPDATE assets SET country='Botsuana' WHERE country='Botswana';
UPDATE assets SET country='Brasil' WHERE country='Brazil';
UPDATE assets SET country='Brunéi' WHERE country='Brunei';
UPDATE assets SET country='Camboya' WHERE country='Cambodia';
UPDATE assets SET country='Camerún' WHERE country='Cameroon';
UPDATE assets SET country='Canadá' WHERE country='Canada';
UPDATE assets SET country='Cabo Verde' WHERE country='Cape Verde';
UPDATE assets SET country='República Centroafricana' WHERE country='Central African Republic';
UPDATE assets SET country='Comoras' WHERE country='Comoros';
UPDATE assets SET country='Croacia' WHERE country='Croatia';
UPDATE assets SET country='Chipre' WHERE country='Cyprus';
UPDATE assets SET country='República Checa' WHERE country='Czech Republic';
UPDATE assets SET country='Dinamarca' WHERE country='Denmark';
UPDATE assets SET country='Yibuti' WHERE country='Djibouti';
UPDATE assets SET country='República Dominicana' WHERE country='Dominican Republic';
UPDATE assets SET country='Egipto' WHERE country='Egypt';
UPDATE assets SET country='Guinea Ecuatorial' WHERE country='Equatorial Guinea';
UPDATE assets SET country='Esuatini' WHERE country='Eswatini';
UPDATE assets SET country='Etiopía' WHERE country='Ethiopia';
UPDATE assets SET country='Fiyi' WHERE country='Fiji';
UPDATE assets SET country='Finlandia' WHERE country='Finland';
UPDATE assets SET country='Francia' WHERE country='France';
UPDATE assets SET country='Gabón' WHERE country='Gabon';
UPDATE assets SET country='Alemania' WHERE country='Germany';
UPDATE assets SET country='Grecia' WHERE country='Greece';
UPDATE assets SET country='Granada' WHERE country='Grenada';
UPDATE assets SET country='Guinea-Bisáu' WHERE country='Guinea-Bissau';
UPDATE assets SET country='Haití' WHERE country='Haiti';
UPDATE assets SET country='Hungría' WHERE country='Hungary';
UPDATE assets SET country='Islandia' WHERE country='Iceland';
UPDATE assets SET country='Irán' WHERE country='Iran';
UPDATE assets SET country='Irak' WHERE country='Iraq';
UPDATE assets SET country='Irlanda' WHERE country='Ireland';
UPDATE assets SET country='Italia' WHERE country='Italy';
UPDATE assets SET country='Costa de Marfil' WHERE country='Ivory Coast';
UPDATE assets SET country='Japón' WHERE country='Japan';
UPDATE assets SET country='Jordania' WHERE country='Jordan';
UPDATE assets SET country='Kazajistán' WHERE country='Kazakhstan';
UPDATE assets SET country='Kenia' WHERE country='Kenya';
UPDATE assets SET country='Kirguistán' WHERE country='Kyrgyzstan';
UPDATE assets SET country='Letonia' WHERE country='Latvia';
UPDATE assets SET country='Líbano' WHERE country='Lebanon';
UPDATE assets SET country='Lesoto' WHERE country='Lesotho';
UPDATE assets SET country='Libia' WHERE country='Libya';
UPDATE assets SET country='Lituania' WHERE country='Lithuania';
UPDATE assets SET country='Luxemburgo' WHERE country='Luxembourg';
UPDATE assets SET country='Malaui' WHERE country='Malawi';
UPDATE assets SET country='Malasia' WHERE country='Malaysia';
UPDATE assets SET country='Maldivas' WHERE country='Maldives';
UPDATE assets SET country='Malí' WHERE country='Mali';
UPDATE assets SET country='Islas Marshall' WHERE country='Marshall Islands';
UPDATE assets SET country='Mauricio' WHERE country='Mauritius';
UPDATE assets SET country='México' WHERE country='Mexico';
UPDATE assets SET country='Moldavia' WHERE country='Moldova';
UPDATE assets SET country='Mónaco' WHERE country='Monaco';
UPDATE assets SET country='Marruecos' WHERE country='Morocco';
UPDATE assets SET country='Birmania' WHERE country='Myanmar';
UPDATE assets SET country='Países Bajos' WHERE country='Netherlands';
UPDATE assets SET country='Nueva Zelanda' WHERE country='New Zealand';
UPDATE assets SET country='Níger' WHERE country='Niger';
UPDATE assets SET country='Corea del Norte' WHERE country='North Korea';
UPDATE assets SET country='Macedonia del Norte' WHERE country='North Macedonia';
UPDATE assets SET country='Noruega' WHERE country='Norway';
UPDATE assets SET country='Omán' WHERE country='Oman';
UPDATE assets SET country='Pakistán' WHERE country='Pakistan';
UPDATE assets SET country='Palaos' WHERE country='Palau';
UPDATE assets SET country='Palestina' WHERE country='Palestine';
UPDATE assets SET country='Panamá' WHERE country='Panama';
UPDATE assets SET country='Papúa Nueva Guinea' WHERE country='Papua New Guinea';
UPDATE assets SET country='Perú' WHERE country='Peru';
UPDATE assets SET country='Filipinas' WHERE country='Philippines';
UPDATE assets SET country='Polonia' WHERE country='Poland';
UPDATE assets SET country='Catar' WHERE country='Qatar';
UPDATE assets SET country='Rumanía' WHERE country='Romania';
UPDATE assets SET country='Rusia' WHERE country='Russia';
UPDATE assets SET country='Ruanda' WHERE country='Rwanda';
UPDATE assets SET country='San Cristóbal y Nieves' WHERE country='Saint Kitts and Nevis';
UPDATE assets SET country='Santa Lucía' WHERE country='Saint Lucia';
UPDATE assets SET country='San Vicente y las Granadinas' WHERE country='Saint Vincent and the Grenadines';
UPDATE assets SET country='Santo Tomé y Príncipe' WHERE country='Sao Tome and Principe';
UPDATE assets SET country='Arabia Saudita' WHERE country='Saudi Arabia';
UPDATE assets SET country='Sierra Leona' WHERE country='Sierra Leone';
UPDATE assets SET country='Singapur' WHERE country='Singapore';
UPDATE assets SET country='Eslovaquia' WHERE country='Slovakia';
UPDATE assets SET country='Eslovenia' WHERE country='Slovenia';
UPDATE assets SET country='Islas Salomón' WHERE country='Solomon Islands';
UPDATE assets SET country='Sudáfrica' WHERE country='South Africa';
UPDATE assets SET country='Corea del Sur' WHERE country='South Korea';
UPDATE assets SET country='Sudán del Sur' WHERE country='South Sudan';
UPDATE assets SET country='España' WHERE country='Spain';
UPDATE assets SET country='Sudán' WHERE country='Sudan';
UPDATE assets SET country='Surinam' WHERE country='Suriname';
UPDATE assets SET country='Suecia' WHERE country='Sweden';
UPDATE assets SET country='Suiza' WHERE country='Switzerland';
UPDATE assets SET country='Siria' WHERE country='Syria';
UPDATE assets SET country='Taiwán' WHERE country='Taiwan';
UPDATE assets SET country='Tayikistán' WHERE country='Tajikistan';
UPDATE assets SET country='Tailandia' WHERE country='Thailand';
UPDATE assets SET country='Timor Oriental' WHERE country='Timor-Leste';
UPDATE assets SET country='Trinidad y Tobago' WHERE country='Trinidad and Tobago';
UPDATE assets SET country='Túnez' WHERE country='Tunisia';
UPDATE assets SET country='Turquía' WHERE country='Turkey';
UPDATE assets SET country='Turkmenistán' WHERE country='Turkmenistan';
UPDATE assets SET country='Ucrania' WHERE country='Ukraine';
UPDATE assets SET country='Emiratos Árabes Unidos' WHERE country='United Arab Emirates';
UPDATE assets SET country='Reino Unido' WHERE country='United Kingdom';
UPDATE assets SET country='Estados Unidos' WHERE country='United States';
UPDATE assets SET country='Uzbekistán' WHERE country='Uzbekistan';
UPDATE assets SET country='Ciudad del Vaticano' WHERE country='Vatican City';
UPDATE assets SET country='Zimbabue' WHERE country='Zimbabwe';
UPDATE assets SET country='México' WHERE country='Mexico';
UPDATE assets SET country='México' WHERE country='Méjico';
UPDATE assets SET country='Perú' WHERE country='Peru';
UPDATE assets SET country='Panamá' WHERE country='Panama';
UPDATE assets SET country='España' WHERE country='Espana';
UPDATE assets SET country='Estados Unidos' WHERE country='USA';
UPDATE assets SET country='Estados Unidos' WHERE country='U.S.A.';
UPDATE assets SET country='Estados Unidos' WHERE country='US';
UPDATE assets SET country='Estados Unidos' WHERE country='U.S.';
UPDATE assets SET country='Estados Unidos' WHERE country='EEUU';
UPDATE assets SET country='Estados Unidos' WHERE country='EE.UU.';
UPDATE assets SET country='Estados Unidos' WHERE country='EE UU';
UPDATE assets SET country='Reino Unido' WHERE country='UK';
UPDATE assets SET country='Reino Unido' WHERE country='U.K.';
UPDATE assets SET country='Brasil' WHERE country='Brasil ';
UPDATE assets SET country='Ucrania' WHERE country='Ucrania ';
UPDATE assets SET country='Panamá' WHERE country='Panamá ';
UPDATE assets SET country='República Dominicana' WHERE country='Republica Dominicana';
UPDATE assets SET country='Perú' WHERE country='Peru ';
UPDATE assets SET country='Emiratos Árabes Unidos' WHERE country='Emiratos Arabes Unidos';
UPDATE assets SET country='Bélgica' WHERE country='Belgica';
UPDATE assets SET country='Japón' WHERE country='Japon';
UPDATE assets SET country='Líbano' WHERE country='Libano';
UPDATE assets SET country='Turquía' WHERE country='Turquia';
UPDATE assets SET country='Rumanía' WHERE country='Rumania';
UPDATE assets SET country='Etiopía' WHERE country='Etiopia';
UPDATE assets SET country='Haití' WHERE country='Haiti';
UPDATE assets SET country='Irán' WHERE country='Iran';
UPDATE assets SET country='Nigeria' WHERE country='Nigeria ';

-- Trim stray leading/trailing whitespace
UPDATE users SET country=TRIM(country) WHERE country IS NOT NULL AND country<>TRIM(country);
UPDATE assets SET country=TRIM(country) WHERE country IS NOT NULL AND country<>TRIM(country);
